import asyncio
import logging
from typing import Any, List, Optional, Tuple
from beliefstate.tracker import BeliefTracker, session_context
from beliefstate.call import LLMCall, LLMResponse

logger = logging.getLogger(__name__)

try:
    from openai import AsyncOpenAI

    HAS_OPENAI = True
except ImportError:
    AsyncOpenAI = Any
    HAS_OPENAI = False


def process_openai_assistant_message(
    thread_messages: List[Any], run_id: str
) -> Tuple[LLMCall, LLMResponse]:
    """
    Reconstructs the LLMCall and LLMResponse from the thread messages for a specific run.
    thread_messages should be a list of OpenAI Message objects (ordered newest first, as returned by API).
    """
    response_texts = []
    call_messages = []

    found_run_msg = False
    for msg in thread_messages:
        # Check if this message was generated by our run
        is_run_msg = getattr(msg, "run_id", None) == run_id

        # Extract content text
        text_content = ""
        content_blocks = getattr(msg, "content", [])
        if isinstance(content_blocks, list):
            for block in content_blocks:
                block_type = getattr(block, "type", "")
                if block_type == "text":
                    text_val = getattr(getattr(block, "text", None), "value", "")
                    text_content += text_val
        elif isinstance(content_blocks, str):
            text_content = content_blocks

        role = getattr(msg, "role", "user")

        if is_run_msg:
            found_run_msg = True
            response_texts.insert(0, text_content)  # Keep chronological order
        else:
            if found_run_msg:
                call_messages.insert(0, {"role": role, "content": text_content})
            else:
                # Newer message than our run, skip
                pass

    # Fallback: if we didn't find any message with run_id, or if there is no context
    if not found_run_msg and thread_messages:
        newest = thread_messages[0]
        text_content = ""
        content_blocks = getattr(newest, "content", [])
        if isinstance(content_blocks, list):
            for block in content_blocks:
                block_type = getattr(block, "type", "")
                if block_type == "text":
                    text_val = getattr(getattr(block, "text", None), "value", "")
                    text_content += text_val
        elif isinstance(content_blocks, str):
            text_content = content_blocks
        response_texts = [text_content]

        for msg in thread_messages[1:]:
            msg_text = ""
            msg_blocks = getattr(msg, "content", [])
            if isinstance(msg_blocks, list):
                for block in msg_blocks:
                    block_type = getattr(block, "type", "")
                    if block_type == "text":
                        text_val = getattr(getattr(block, "text", None), "value", "")
                        msg_text += text_val
            elif isinstance(msg_blocks, str):
                msg_text = msg_blocks
            call_messages.insert(
                0, {"role": getattr(msg, "role", "user"), "content": msg_text}
            )

    response_text = "\n".join(response_texts)
    llm_call = LLMCall(messages=call_messages)

    # Safely convert thread messages to dictionary for raw response serialization
    raw_msgs = []
    for m in thread_messages:
        try:
            if hasattr(m, "model_dump"):
                raw_msgs.append(m.model_dump())
            elif hasattr(m, "dict"):
                raw_msgs.append(m.dict())
            else:
                raw_msgs.append(str(m))
        except Exception:
            raw_msgs.append(str(m))

    llm_response = LLMResponse(
        text=response_text, raw_response={"thread_messages": raw_msgs}
    )
    return llm_call, llm_response


async def observe_run(
    tracker: BeliefTracker,
    client: Any,
    thread_id: str,
    run_id: str,
    session_id: Optional[str] = None,
    poll_interval: float = 1.0,
) -> None:
    """
    Polls an OpenAI Assistant Run until completion, then reconstructs the messages
    and dispatches them to the BeliefTracker.
    """
    if not HAS_OPENAI and not hasattr(client, "beta"):
        logger.warning("OpenAI client wrapper is being used without standard library.")

    sid = session_id or session_context.get()

    while True:
        run = await client.beta.threads.runs.retrieve(
            thread_id=thread_id, run_id=run_id
        )
        status = getattr(run, "status", "failed")
        if status in ("completed", "failed", "cancelled", "expired"):
            if status != "completed":
                logger.error(
                    f"OpenAI Assistant Run {run_id} finished with status: {status}"
                )
                return
            break
        await asyncio.sleep(poll_interval)

    # Fetch messages once completed
    messages_cursor = await client.beta.threads.messages.list(thread_id=thread_id)
    thread_messages = list(messages_cursor.data)

    call, response = process_openai_assistant_message(thread_messages, run_id)

    tracker.turn_counter += 1
    current_turn = tracker.turn_counter

    if tracker.config.enable_background_tasks:
        tracker.dispatcher.dispatch(tracker, call, response, sid, current_turn)
    else:
        await tracker._track_background(call, response, sid, current_turn)
